### ISSUE TITLE
UserManager.CreateAsync() not calling UserStore.CreateAsync()

### ISSUE THREAD

**Issue by SimonKunz** [cskardon/Neo4j.AspNet.Identity#4] opened 2015-01-16 22:56 UTC
After calling UserManger.CreateAsync() the CreateAsync()-Method of the UserStore is not called. Instead the following Methods on the UserStore are called:

SetPasswordHashAsync() 
SetSecurityStampAsync() (2 times)
FindByNameAsync()
GetEmailAsync()

Someone is having similar problems here: https://aspnetidentity.codeplex.com/discussions/570458

I'm not 100% sure if this is a bug in this implementation of identity or if I'm having a bug in my code. If that's the case, I'm sorry. But I just can't figure this out.

**Comment by zxehf** [comment] 2015-05-26 15:41
I ran into the exact same issue.

I found a hint for the solution here:  http://stackoverflow.com/questions/25502111/asp-net-identity-attempting-to-add-user-with-existing-id

Root cause of the problem in my code was that my FindByNameAsync implementation was not returning null for user not found.  This broke the flow resulting in no call to CreateAsync.

**Comment by cskardon** [comment] 2015-06-04 15:13
Do you have a way to replicate this, the code base I'm working off (which is *not* the nuget version) *does* return null if the user isn't found from the FindByNameAsync method. 

I only wrote my fork (and subsequent pull) because of problems I ran into - quite possibly this was one of them. 

I can only ask that you try compiling the code and using the `Neo4jUserStore` to see if this solves that problem.

**Comment by cskardon** [comment] 2015-10-28 10:42
Closing this as no feedback :/

**Closed by cskardon** 2015-10-28 10:42 UTC

**Comment by KodiKraig** [comment] 2018-04-13 03:02
Ok so I spent half a day on this problem and just came across the fix randomly going through someones GitHub project. Apparently you cant just return a "normal" null. You need: 

`Task.FromResult<AppUser>(null)`

I know this was like 3 years ago but I had to post it just incase someone finds their way here.

**Comment by zico7** [comment] 2020-12-15 19:31
I know this is like 2 and a half years ago but this just saved me. High 5 !! @KodiKraig 👍
